### ISSUE TITLE
GPT4ALL GLIBCXX missing

### ISSUE THREAD

**Issue by priamai** [modal-labs/modal-client#1062]
Hi there:

```
import modal

def download_model():
    import gpt4all
    print("Initializing ORCA Minig....")
    #you can use any model from https://gpt4all.io/models/models2.json
    model = gpt4all.GPT4All("mistral-7b-openorca.Q4_0.gguf")
    return model

image=modal.Image.debian_slim().pip_install("gpt4all").run_function(download_model)
stub = modal.Stub("gpt4all", image=image)
@stub.cls(keep_warm=1)
class GPT4AllChat:
    def __enter__(self):
        print("Downloading model")
        self.gptj = download_model()
        print("Loaded model")

    @modal.method()
    def generate(self):
        messages = [{"role": "user", "content": "Name 3 colors"}]
        completion = self.gptj.chat_completion(messages)
        print(f"Completion: {completion}")

@stub.local_entrypoint()
def main_old():
    model = GPT4AllChat()
    for i in range(10):
        model.generate.remote()
```
I am getting a library issue:

```
RemoteError: Image build for im-Arbk6QjxvEerqHIijMkS1g failed with the
exception:
OSError("/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not
found (required by
/usr/local/lib/python3.11/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libl
lmodel.so)")
```
What packages I should install to fix it?

**Comment by ekzhang** [comment]
Looks like they already responded on your other issue. If you want to use Ubuntu 22.04 as they suggest on the GPT4All repo, you can do this:

```python
Image.from_registry("ubuntu:22.04")
```

**Comment by priamai** [comment]
Yes thanks this worked:

**Comment by priamai** [comment]
wait @ekzhang I am getting an error now with the example above:
```

Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 342, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 480, in run_inputs
    function_io_manager.push_output(input_id, started_at, output_index.value, res, imp_fun.data_format)
  File "/pkg/synchronicity/synchronizer.py", line 497, in proxy_method
    return wrapped_method(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/synchronicity/combined_types.py", line 26, in __call__
    raise uc_exc.exc from None
  File "/pkg/modal/_container_entrypoint.py", line 381, in push_output
    data=self.serialize_data_format(data, data_format),
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/modal/_container_entrypoint.py", line 161, in serialize_data_format
    return serialize_data_format(obj, data_format)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pkg/modal/_serialization.py", line 172, in serialize_data_format
    return serialize(obj)
           ^^^^^^^^^^^^^^
  File "/pkg/modal/_serialization.py", line 52, in serialize
    Pickler(buf).dump(obj)
  File "/usr/local/lib/python3.11/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
ValueError: ctypes objects containing pointers cannot be pickled
Creating image snapshot...
Finished snapshot; took 4.97s
Finished image build for im-Xyy31jy8jf2TVFStDfl2mf
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ <frozen runpy>:198 in _run_module_as_main                                    │
│                                                                              │
│ <frozen runpy>:88 in _run_code                                               │
│                                                                              │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ modal/__main__.py:13 in <module>                                             │
│                                                                              │
│   12 if __name__ == "__main__":                                              │
│ ❱ 13 │   main()                                                              │
│   14                                                                         │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ modal/__main__.py:9 in main                                                  │
│                                                                              │
│    8 │   setup_rich_traceback()                                              │
│ ❱  9 │   entrypoint_cli()                                                    │
│   10                                                                         │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ click/core.py:1157 in __call__                                               │
│                                                                              │
│   1156 │   │   """Alias for :meth:`main`."""                                 │
│ ❱ 1157 │   │   return self.main(*args, **kwargs)                             │
│   1158                                                                       │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ typer/core.py:778 in main                                                    │
│                                                                              │
│   777 │   ) -> Any:                                                          │
│ ❱ 778 │   │   return _main(                                                  │
│   779 │   │   │   self,                                                      │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ typer/core.py:216 in _main                                                   │
│                                                                              │
│   215 │   │   │   with self.make_context(prog_name, args, **extra) as ctx:   │
│ ❱ 216 │   │   │   │   rv = self.invoke(ctx)                                  │
│   217 │   │   │   │   if not standalone_mode:                                │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ click/core.py:1688 in invoke                                                 │
│                                                                              │
│   1687 │   │   │   │   with sub_ctx:                                         │
│ ❱ 1688 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub │
│   1689                                                                       │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ click/core.py:1688 in invoke                                                 │
│                                                                              │
│   1687 │   │   │   │   with sub_ctx:                                         │
│ ❱ 1688 │   │   │   │   │   return _process_result(sub_ctx.command.invoke(sub │
│   1689                                                                       │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ click/core.py:1434 in invoke                                                 │
│                                                                              │
│   1433 │   │   if self.callback is not None:                                 │
│ ❱ 1434 │   │   │   return ctx.invoke(self.callback, **ctx.params)            │
│   1435                                                                       │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ click/core.py:783 in invoke                                                  │
│                                                                              │
│    782 │   │   │   with ctx:                                                 │
│ ❱  783 │   │   │   │   return __callback(*args, **kwargs)                    │
│    784                                                                       │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ click/decorators.py:33 in new_func                                           │
│                                                                              │
│    32 │   def new_func(*args: "P.args", **kwargs: "P.kwargs") -> "R":        │
│ ❱  33 │   │   return f(get_current_context(), *args, **kwargs)               │
│    34                                                                        │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ modal/cli/run.py:145 in f                                                    │
│                                                                              │
│   144 │   │                                                                  │
│ ❱ 145 │   │   with run_stub(                                                 │
│   146 │   │   │   stub,                                                      │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ synchronicity/synchronizer.py:497 in proxy_method                            │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ synchronicity/combined_types.py:26 in __call__                               │
│                                                                              │
│ /usr/lib/python3.11/contextlib.py:204 in __aenter__                          │
│                                                                              │
│   203 │   │   try:                                                           │
│ ❱ 204 │   │   │   return await anext(self.gen)                               │
│   205 │   │   except StopAsyncIteration:                                     │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ modal/runner.py:93 in _run_stub                                              │
│                                                                              │
│    92 │   │   │   # Create all members                                       │
│ ❱  93 │   │   │   await app._create_all_objects(                             │
│    94 │   │   │   │   stub._blueprint, app_state, environment_name, shell=sh │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ modal/app.py:106 in _create_all_objects                                      │
│                                                                              │
│   105 │   │   │   │   existing_object_id = tag_to_object_id.get(tag)         │
│ ❱ 106 │   │   │   │   await resolver.load(obj, existing_object_id)           │
│   107 │   │   │   │   self._tag_to_object_id[tag] = obj.object_id            │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ modal/_resolver.py:131 in load                                               │
│                                                                              │
│   130 │   │                                                                  │
│ ❱ 131 │   │   return await cached_future                                     │
│   132                                                                        │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ modal/_resolver.py:107 in loader                                             │
│                                                                              │
│   106 │   │   │   │   # Load the object itself                               │
│ ❱ 107 │   │   │   │   await obj._load(obj, self, existing_object_id)         │
│   108 │   │   │   │   if existing_object_id is not None and obj.object_id != │
│                                                                              │
│ /home/robomotic/DevOps/gitlab/ava-prod-ai/venv/lib/python3.11/site-packages/ │
│ modal/image.py:317 in _load                                                  │
│                                                                              │
│    316 │   │   │   if result.status == api_pb2.GenericResult.GENERIC_STATUS_ │
│ ❱  317 │   │   │   │   raise RemoteError(f"Image build for {image_id} failed │
│    318 │   │   │   elif result.status == api_pb2.GenericResult.GENERIC_STATU │
╰──────────────────────────────────────────────────────────────────────────────╯
RemoteError: Image build for im-Xyy31jy8jf2TVFStDfl2mf failed with the 
exception:
ValueError('ctypes objects containing pointers cannot be pickled')
```
