### ISSUE TITLE
Terminating task due to error: CMD not supported

### ISSUE THREAD

**Issue by priamai** [modal-labs/modal-client#1065]
Hayoooo,
I am trying to run the OLLAMA server as a docker image.
Here's my attempt so far:
```

import json
import os
import subprocess

from modal import Image, Secret, Stub, web_endpoint

ollama_image = Image.from_registry(
    "ollama/ollama",
    add_python="3.11",
    setup_dockerfile_commands=['ENTRYPOINT ["/bin/ollama"]','CMD ["serve"]'],
)

stub = Stub("ollama-server")

@stub.function(
    image=ollama_image
)
def download_model():

    subprocess.run(
        ["ollama", "pull", "mistral7b"],
        env={**os.environ},
    )


@stub.local_entrypoint()
def run():
    download_model.remote()

```
```

This is the error:

Building image im-V7KNUgkjZ8YMdToYiBB1NL

=> Step 0: FROM ollama/ollama
Getting image source signatures
Copying blob sha256:ece965e642055f2e0132b7e852c02d8ba193538e9dac14794dfba24e12ee366d
Copying blob sha256:aece8493d3972efa43bfd4ee3cdba659c0f787f8f59c82fb3e48c87cbb22a12e
Copying blob sha256:3b9196308e0f6c75d845f81026884e381c5fe995ebce0c559dd390acc2655013
Copying config sha256:871fb7f12b8c62a0996cedd4a5b045c971b3a1a53f6660df288cd6679bab92ab
Writing manifest to image destination
Unpacking OCI image
   • unpacking rootfs ...
   • ... done
   • unpacked image rootfs: /tmp/.tmpsq3quY

=> Step 1: COPY /python/. /usr/local

=> Step 2: RUN ln -s /usr/local/bin/python3 /usr/local/bin/python

=> Step 3: ENV TERMINFO_DIRS=/etc/terminfo:/lib/terminfo:/usr/share/terminfo:/usr/lib/terminfo

=> Step 4: ENTRYPOINT ["/bin/ollama"]

=> Step 5: CMD ["serve"]
Terminating task due to error: CMD not supported
Runner failed with exception: task exited with failure, status = exit status: 1
```

So I tried:

```
ollama_image = Image.from_registry(
    "ollama/ollama",
    add_python="3.11",
    setup_dockerfile_commands=['ENTRYPOINT ["/bin/ollama serve"]'],
)

```

But then I get:
```
Built image im-oN72gJiKN3qGnZIcB6W1QA in 38.24s
✓ Created objects.
├── 🔨 Created mount /home/robomotic/DevOps/github/causalbot/ollama/modalabs/runollama.py
└── 🔨 Created download_model.
[dumb-init] /bin/ollama serve: No such file or directory
Runner failed with exit code: 2
```

This is the dockerfile for reference:
`https://github.com/jmorganca/ollama/blob/main/Dockerfile`

**Comment by luiscape** [comment]
Hi @priamai, I suggest you do the following to debug this app:

1. remove `ENTRYPOINT` and then use a [modal shell](https://modal.com/docs/reference/cli/shell#modal-shell) to investigate if the binaries are available, have been correctly installed, etc. 
2. serve ollama using a [Modal Tunnel](https://modal.com/docs/guide/tunnels#tunnels-beta)

Let me know if that works.

**Comment by priamai** [comment]
Hello thanks for the suggestion,so I changed it like so:

```
import json
import os
import subprocess

from modal import Image, Secret, Stub, web_endpoint

ollama_image = Image.from_registry(
    "ollama/ollama",
    add_python="3.11",
    setup_dockerfile_commands=[],
)

stub = Stub("ollama-server")

@stub.function(
    image=ollama_image
)
def download_model():

    subprocess.run(
        ["ollama", "pull", "mistral7b"],
        env={**os.environ},
    )


@stub.local_entrypoint()
def run():
    download_model.remote()
```

Then I run: modal shell myfile.py but it seems to trigger the download_model, how do I just get a shell inside the image?

```
✓ Created objects.
├── 🔨 Created mount /home/robomotic/DevOps/github/causalbot/ollama/modalabs/runollama.py
└── 🔨 Created download_model.
Error: unknown command "python" for "ollama"
                                            Runner failed with exit code: 1
                                                                           Error: unknown command "python" for "ollama"
                                                                                                                       Runner failed with exit code: 1
                                                                                                                                                      Error: unknown command "python" for "ollama"
                                  Runner failed with exit code: 1
                                                                 Error: unknown command "python" for "ollama"
```

**Comment by priamai** [comment]
Also tried:

**Comment by priamai** [comment]
Wow a couple of questions as I want to learn:
A) the entrypoint bash file: why do we need it? What's inside it? It's stored on your local folder?
B) why my shell attempt failed to get a command? Do I need to specify a specific SSH tunnell?
C) modal tunnell: can it be used to add for example basic HTTP authentication?

Thanks a lot for the help.

**Comment by priamai** [comment]
It all makes sense now, in fact when I run the shell inside the container I see exactly my local python file.

Just a minor thing,I have an error on the tls_socket print out (i commented it out for now):

```
Traceback (most recent call last):
  File "/pkg/modal/_container_entrypoint.py", line 342, in handle_input_exception
    yield
  File "/pkg/modal/_container_entrypoint.py", line 460, in run_inputs
    res = imp_fun.fun(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ollama_service.py", line 84, in serve
    print(f"tunnel.tls_socket = {tunnel.tls_socket}")
                                 ^^^^^^^^^^^^^^^^^
AttributeError: 'Tunnel' object has no attribute 'tls_socket'
```
Yes I can play with the FASTAPI authenticator, it should be very easy.

Also another more complex setup question: let's say I want to run 2 containers (like the one I have in my docker composer file) where they use the internal network to communicate but only one is exposed to public interface, is this possible to replicate in modal?

**Comment by priamai** [comment]
This is my first attempt:

```
import sys
import time
import subprocess

import modal

# Default server port.
OLLAMA_PORT: int = 11434


def _run_subprocess(cmd: list[str], block: bool = True) -> None:
    if block:
        subprocess.run(
            cmd,
            stdout=sys.stdout,
            stderr=sys.stderr,
            check=True,
        )
    else:
        subprocess.Popen(
            cmd,
            stdout=sys.stdout,
            stderr=sys.stderr,
        )


def _is_server_healthy(port: int = OLLAMA_PORT) -> bool:
    url = f"http://localhost:{port}/"
    try:
        response = requests.get(url)
        if response.ok:
            print(f"Successfully made a request to {url}")
            return True
        else:
            print(f"Received a non-success status code from {url}")
            return False
    except requests.RequestException as e:
        print(f"Error making a request to {url}: {e}")
        return False


def download_model():
    _run_subprocess(["ollama", "serve"], block=False)
    while not _is_server_healthy():
        print("waiting for server to start ...")
        time.sleep(1)

    _run_subprocess(["ollama", "pull", "mistral"])


image = (
    modal.Image.from_registry(
        "ollama/ollama",
        add_python="3.11",
    )
    .pip_install("requests")  # for healthchecks
    .copy_local_file("./entrypoint.sh", "/opt/entrypoint.sh")
    .dockerfile_commands(
        [
            "RUN chmod a+x /opt/entrypoint.sh",
            'ENTRYPOINT ["/opt/entrypoint.sh"]',
        ]
    )
    .run_function(download_model)
)

stub = modal.Stub("ollama-server", image=image)

with stub.image.run_inside():
    import requests

from modal import Secret, Stub, web_endpoint

from fastapi import Depends, HTTPException, status, Request,Response
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials

auth_scheme = HTTPBearer()


@stub.function(secret=Secret.from_name("ollama-secret"))
@web_endpoint()
async def f(request: Request, token: HTTPAuthorizationCredentials = Depends(auth_scheme)):
    import os

    print(os.environ["OLLAMA_AUTH_TOKEN"])
    print(request.url)

    if token.credentials != os.environ["OLLAMA_AUTH_TOKEN"]:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Incorrect bearer token",
            headers={"WWW-Authenticate": "Bearer"},
        )
    else:
        url = f"http://localhost:{OLLAMA_PORT}/"
        try:
            int_response = requests.get(url)

            return Response(content=int_response.content)
        except Exception:
            raise HTTPException(status_code=int_response.status_code)


@stub.function()
def serve():
    # Start Ollama server.
    _run_subprocess(["ollama", "serve"], block=False)
    while not _is_server_healthy():
        print("waiting for server to start ...")
        time.sleep(1)

    # Serve Ollama forever; expose server via Modal Tunnel.
    with modal.forward(OLLAMA_PORT) as tunnel:
        print(f"tunnel.url        = {tunnel.url}")
        #print(f"tunnel.tls_socket = {tunnel.tls_socket}")
        while True:
            time.sleep(1)


@stub.local_entrypoint()
def run():
    serve.remote()

```

I am guessing I will then need to disable the tunnel and just keep the web_endpoint.
Is the endpoint going to catch all the possible URLS? So effectively I can just replicate the path to the local server?

Cheers!

**Comment by luiscape** [comment]
That's about right. You'll have to do a bit more than just this

```
    else:
        url = f"http://localhost:{OLLAMA_PORT}/"
        try:
            int_response = requests.get(url)

            return Response(content=int_response.content)
        except Exception:
            raise HTTPException(status_code=int_response.status_code)
```
in order to proxy the request correctly (you need to pass the URL path and data [request body?]) but that's in the right path.

I am going to close this issue for now. Can you [join our community Slack](https://join.slack.com/t/modalbetatesters/shared_invite/zt-23ylw1o1y-hUDY8a5cpBdUCiPKqL19Cg) so we can keep chatting about this?
