### ISSUE TITLE
error with cli commad: `modal deploy`

### ISSUE THREAD

**Issue by fcakyon** [modal-labs/modal-client#1150]
## reproduction

python 3.10
macos 14.0
mba m2
modal-client 10894ffefc4d54c98e85974b5642424bb55c46e1

```bash
modal deploy modal_deploy.py
```

```python
# modal_deploy.py

from pathlib import Path
from modal import Image, Mount, Secret, Stub, asgi_app
from api.v2.app import app as web_app

CONTAINER_IDLE_TIME = 1200  # 20 minutes
REQUEST_TIMEOUT = 10  # 10 seconds
CONCURRENCY_LIMIT = 10

# Initialize Modal and install necessary packages
stub = Stub(
    name="..."
)
image = (
    Image.debian_slim(python_version="3.10", force_build=False)
    .apt_install('git')
    .pip_install_from_requirements("requirements.txt")
)


@stub.function(
    image=image,
    mounts=[
        Mount.from_local_file(Path(".env").resolve(), remote_path="/root/.env"),
    ],
    secrets=[Secret.from_name("...")],
    container_idle_timeout=CONTAINER_IDLE_TIME,
    timeout=REQUEST_TIMEOUT,
    concurrency_limit=CONCURRENCY_LIMIT,
)
@asgi_app()
def app():
    return web_app
```

## error:

```bash
################################################################################
#             Something with the Modal installation seems broken.              #
#           Please email support@modal.com and we will try to help!            #
################################################################################

Traceback (most recent call last):
  File "/Users/.../miniconda3/envs/.../bin/modal", line 5, in <module>
    from modal.__main__ import main
  File "/Users/.../miniconda3/envs/s.../lib/python3.10/site-packages/modal/__init__.py", line 13, in <module>
    from ._tunnel import Tunnel, forward
  File "/Users/.../miniconda3/envs/.../lib/python3.10/site-packages/modal/_tunnel.py", line 10, in <module>
    from modal_proto import api_pb2
ImportError: cannot import name 'api_pb2' from 'modal_proto' (/Users/.../miniconda3/envs/.../lib/python3.10/site-packages/modal_proto/__init__.py)
```

**Comment by ekzhang** [comment]
There might be a problem with the installation. Could you please try:

```
pip uninstall modal modal-client
pip install modal
```

If that still doesn't work, could you let us know the output of:

```
pip freeze
```

**Comment by thundergolfer** [comment]
Following up here. @fcakyon did the install issue get resolved?

**Comment by thundergolfer** [comment]
Closing as inactive. Can reopen if needed :)
