### ISSUE TITLE
with_options cpu options does not work as expected

### ISSUE THREAD

**Issue by andersonbcdefg** [modal-labs/modal-client#1314]
This PR (#1222) added support for a cpu argument to with_options. However, when I try to use this option with the latest modal client, it doesn't seem to be supported by the underlying proto:

```
c = modal.Cls.lookup("my_app", "my_class").with_options(cpu=8.0)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/benjamin/.pyenv/versions/taylor-server/lib/python3.9/site-packages/synchronicity/synchronizer.py", line 526, in proxy_method
    return wrapped_method(instance, *args, **kwargs)
  File "/Users/benjamin/.pyenv/versions/taylor-server/lib/python3.9/site-packages/synchronicity/synchronizer.py", line 421, in f_wrapped
    res = f(*args, **kwargs)
  File "/Users/benjamin/.pyenv/versions/taylor-server/lib/python3.9/site-packages/modal/cls.py", line 283, in with_options
    resources = api_pb2.Resources(cpu=cpu, memory=memory, gpu_config=parse_gpu_config(gpu))
ValueError: Protocol message Resources has no "cpu" field.
```

**Comment by gongy** [comment]
Thanks! Sorry about that. This is fixed in https://github.com/modal-labs/modal-client/pull/1323/files
