### ISSUE TITLE
Hello world fails, 

### ISSUE THREAD

**Issue by loliverhennigh** [modal-labs/modal-client#1351]
Hello world fails due to not having `psutil` installed.

```
✓ Initialized. View run at https://modal.com/loliverhennigh/apps/ap-z7N40vC2o0yhGYjo4OhGRf
✓ Created objects.
├── 🔨 Created mount /home/oliver/unleashed/modal_example/scrape.py
└── 🔨 Created get_links.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/pkg/modal/_container_entrypoint.py", line 38, in <module>
    from ._checkpointing_utils import get_open_connections
  File "/pkg/modal/_checkpointing_utils.py", line 6, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/pkg/modal/_container_entrypoint.py", line 38, in <module>
    from ._checkpointing_utils import get_open_connections
  File "/pkg/modal/_checkpointing_utils.py", line 6, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
Runner failed with exit code: 1

```

Simple fix is to add it to the image. I included an example of this for the scrape example,

```
import re
import urllib.request
import modal

stub = modal.Stub(name="link-scraper")


playwright_image = modal.Image.debian_slim(python_version="3.10").run_commands(
    "apt-get update",
    "apt-get install -y software-properties-common",
    "apt-add-repository non-free",
    "apt-add-repository contrib",
    "pip install playwright==1.30.0 psutil",
    "playwright install-deps chromium",
    "playwright install chromium",
)

@stub.function(image=playwright_image)
async def get_links(cur_url: str):
    from playwright.async_api import async_playwright

    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()
        await page.goto(cur_url)
        links = await page.eval_on_selector_all("a[href]", "elements => elements.map(element => element.href)")
        await browser.close()

    print("Links", links)
    return links

@stub.local_entrypoint()
def main():
    urls = ["http://modal.com", "http://github.com"]
    for links in get_links.map(urls):
        for link in links:
            print(link)
```

**Comment by mwaskom** [comment]
Hi, this was a bug introduced in 0.57.43 and later reverted. If you update your modal client it should work for you now.
