### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'Thread-1 (thread_inner)'.

### ISSUE THREAD

**Issue by alijaafar21** [modal-labs/modal-client#1504]
Hello,

While attempting to invoke a deployed Modal function in a Chainlit application I faced the following error:
```
RuntimeError: There is no current event loop in thread 'Thread-1 (thread_inner)'.
```

This is how I am getting and invoking the function:
```
query_mistral_7b_instruct_v0p2 = modal.Function.from_name(app_name='...', tag='query_mistral_7b_instruct_v0p2')
response = query_mistral_7b_instruct_v0p2.remote('What is the meaning of a word?')
```

Kindly note that the same error was first happening when getting the function through `modal.Function.lookup( )`
but using `modal.Function.from_name( )` made it work.
But now the `.remote( )` is causing the same issue.

Here's the full stack trace:
```
Exception in thread Thread-1 (thread_inner):
Traceback (most recent call last):
  File "...\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "...\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "...\venv\Lib\site-packages\synchronicity\synchronizer.py", line 168, in thread_inner        
    raise exc
  File "...\venv\Lib\site-packages\synchronicity\synchronizer.py", line 162, in thread_inner        
    asyncio.run(loop_inner())
  File "...\venv\Lib\site-packages\nest_asyncio.py", line 26, in run
    loop = asyncio.get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\nest_asyncio.py", line 40, in _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python\Python312\Lib\asyncio\events.py", line 702, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (thread_inner)'.
```

- Python version: `3.12.2`
- Modal Client version: `0.61.31`

**Comment by mwaskom** [comment]
Hey @alijaafar21 just so I understand — is `nest_asyncio` a library you're using in your codebase? Any chance you have a minimal reproducer we could run to understand the underlying issue?

**Comment by alijaafar21** [comment]
Hello,

I am not directly using `nest_asyncio` in my code. But, I am working on a Chainlit app, which perhaps uses it.

I have created the following [repo](https://github.com/alijaafar21/no-current-event-loop-in-thread-minimal-reproducer) which will allow reproducing the error reported above by executing
```
chainlit run app.py
```
In [app.py](https://github.com/alijaafar21/no-current-event-loop-in-thread-minimal-reproducer/blob/main/app.py), I am trying to lookup a function and then invoke it.

Kindly note that if the `try-except` block in `app.py` is uncommented, the error no longer happens.

**Comment by mwaskom** [comment]
Thank you! I suspect that the issue is with the code underlying the `philosophy-question-answerer` app though and it's going to be hard to debug that without knowing what it looks like. Definitely would be easier for us to resolve this if we had a simple example we could run on our end to observe the error, although I appreciate that that may be difficult to produce.

**Comment by alijaafar21** [comment]
Kindly find the code of the function `query_mistral_7b_instruct_v0p2` we are attempting to invoke [here](https://github.com/philosophy-question-answerer/modal-deployment/blob/main/deployed_functions.py)

**Comment by mwaskom** [comment]
Cleaning up our issue tracker — looks like you had a workaround here that unblocked you. Based on my reading it looks like it's not a modal-specific issue and depends on the framework. Going to close with no further action on our side. Feel free to follow up if you're still having issues.
