### ISSUE TITLE
Running Jupyter inside Modal: Uninformative Error Message

### ISSUE THREAD

**Issue by tusharkhot** [modal-labs/modal-client#1715]
When trying to run a Jupyter notebook inside modal, I need to wait before sending my first request otherwise it crashes the app.

Sample simplified code (based on the jupyter_inside_modal example):
```python
import os
import subprocess
import time
import threading
import modal
import requests
stub = modal.Stub(
    image=modal.Image.debian_slim().pip_install(
        "jupyter"
    )
)

queue = modal.Queue.from_name("my-persisted-queue", create_if_missing=True)

CACHE_DIR = "/root/cache"
JUPYTER_TOKEN = "1234"  # Change me to something non-guessable!



# This is all that's needed to create a long-lived Jupyter server process in Modal
# that you can access in your Browser through a secure network tunnel.
# This can be useful when you want to interactively engage with Volume contents
# without having to download it to your host computer.


@stub.function(concurrency_limit=1, timeout=1_500)
def run_jupyter(timeout: int):
    jupyter_port = 8888
    with modal.forward(jupyter_port) as tunnel:
        jupyter_process = subprocess.Popen(
            [
                "jupyter",
                "notebook",
                "--no-browser",
                "--allow-root",
                "--ip=0.0.0.0",
                f"--port={jupyter_port}",
                f"--NotebookApp.token={JUPYTER_TOKEN}",
                "--NotebookApp.password=",
                "--NotebookApp.allow_origin='*'",
                "--NotebookApp.allow_remote_access=1",
            ],
            env={**os.environ},
        )

        print(f"Jupyter available at => {tunnel.url}")
        queue.put(tunnel.url)
        try:
            end_time = time.time() + timeout
            while time.time() < end_time:
                time.sleep(5)
            print(f"Reached end of {timeout} second timeout period. Exiting...")
        except KeyboardInterrupt:
            print("Exiting...")
        finally:
            jupyter_process.kill()


@stub.local_entrypoint()
def main():
    # Run the Jupyter Notebook server
    run_jupyter.spawn(1_500)
    new_url = queue.get()
    url = f"{new_url}/api/kernels?token={JUPYTER_TOKEN}"
    print(f"Creating a new kernel at {url}")
    with requests.post(url) as response:
        print(response)

if __name__ == "__main__":
    with stub.run():
        main()
```

`python script.py` will crash with an uninformative error message: 

```
Stopping app - uncaught exception raised locally: ConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))).
```

But if I add a timeout between the spawn and first request:
```
...
    sleep(5)
    with requests.post(url) as response:
...
```
I dont get any errors. I am guessing it needs some time for jupyter to set up but I dont understand why the app crashes.

**Comment by mwaskom** [comment]
Hi, this more or less makes sense to me: you're putting the URL in the queue as soon as you launch the jupyter subprocess, which takes a few seconds to boot up and actually serve. So you are getting a local connection aborted error from requests. AFAICT, the error is arising from code that you've added to our example, not code that we provide? Let me know if I am missing something though.

**Comment by tusharkhot** [comment]
I was assuming the error was coming from Modal. But I didn't consider that this error was from `requests`. I wish it was more informative but if its coming from `requests`, there isn't much you can do about it. I also incorrectly assumed that the modal app was crashing, but I guess my local code crashing is terminating the ephemeral app?

**Comment by mwaskom** [comment]
> But I didn't consider that this error was from requests

Are you not seeing a traceback? I see

```python-traceback
Traceback (most recent call last):
  File "/Users/mwaskom/scratch/modal-jupyter.py", line 69, in <module>
    main()
  File "/Users/mwaskom/code/modal/venv/lib/python3.11/site-packages/synchronicity/synchronizer.py", line 531, in proxy_method
    return wrapped_method(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwaskom/code/modal/venv/lib/python3.11/site-packages/synchronicity/synchronizer.py", line 422, in f_wrapped
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/Users/mwaskom/code/modal/venv/lib/python3.11/site-packages/modal/stub.py", line 52, in __call__
    return self._info.raw_f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwaskom/scratch/modal-jupyter.py", line 63, in main
    with requests.post(url) as response:
         ^^^^^^^^^^^^^^^^^^
  File "/Users/mwaskom/code/modal/venv/lib/python3.11/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwaskom/code/modal/venv/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwaskom/code/modal/venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwaskom/code/modal/venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mwaskom/code/modal/venv/lib/python3.11/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

> I also incorrectly assumed that the modal app was crashing, but I guess my local code crashing is terminating the ephemeral app?

Yep, I also see this in my console:

> Stopping app - uncaught exception raised locally: ConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))).

**Comment by tusharkhot** [comment]
Because of the order of logging, I see the raw error first
```
Stopping app - uncaught exception raised locally: ConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))).
```
and then the error trace you mentioned. This makes it seem that the app crashed first ("Stopping app") and then my Python code crashed (the stack trace; since there is no running app anymore). This is why I thought the problem must be in the app and not in my code. I didnt realize the implication of `uncaught exception raised locally`. Sorry about the false alarm.
