### ISSUE TITLE
Errors when using parametrized functions in jupyter notebook

### ISSUE THREAD

**Issue by shyamsn97** [modal-labs/modal-client#1846]
Hey! I'm currently having a great time using modal, but running into issues when using the `@cls` decorator in jupyter-notebooks. Here's the code I'm using right now in a single cell:

```python
import modal
from modal import Image, App, method

app = App("test-cls-notebook")
app.image = Image.debian_slim()

@app.cls(gpu="A10G")
class Module:
    def __init__(self, x: int = 10):
        self.x = x

    @method()
    def test(self, y):
        return self.x * y

with app.run():
    model = Module()
    print(model.test.remote(10))
```
---
When running this, I get this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/pkg/modal/_container_entrypoint.py", line 653, in <module>
    main(container_args, client)
  File "/pkg/modal/_container_entrypoint.py", line 575, in main
    pre_snapshot_methods = _find_callables_for_obj(imp_fun.obj, _PartialFunctionFlags.ENTER_PRE_SNAPSHOT)
  File "/pkg/modal/partial_function.py", line 137, in _find_callables_for_obj
    return {k: meth.__get__(user_obj) for k, meth in _find_callables_for_cls(user_cls, flags).items()}
  File "/pkg/modal/partial_function.py", line 128, in _find_callables_for_cls
    for k, pf in _find_partial_methods_for_cls(user_cls, flags).items():
  File "/pkg/modal/partial_function.py", line 93, in _find_partial_methods_for_cls
    if partial_function.flags & flags:
AttributeError: 'PartialFunction' object has no attribute 'flags'
Exception ignored in: <function blocking___del__ at 0x7fb0ab554820>
Traceback (most recent call last):
  File "/pkg/synchronicity/synchronizer.py", line 529, in proxy_method
KeyError: '_sync_original_140396784877472'
```

This works perfectly fine when running it in a script, even with the `app.run()` context, so it seems like it is just a problem when running it in jupyter. Any help would be appreciated!

Modal version: `modal client version: 0.62.181`

**Comment by shyamsn97** [comment]
Thanks so much for this fix 😄
