### ISSUE TITLE
Issue building nvidia apex on modal 

### ISSUE THREAD

**Issue by AvisP** [modal-labs/modal-client#2049]
Hi,

I need to have nvidia apex on a modal container. I have tried to install based on the instructions provided [here](https://github.com/NVIDIA/apex). Created this image container

```
import modal

cuda_version = "12.4.0"  # should be no greater than host CUDA version
flavor = "devel"  #  includes full CUDA toolkit
os = "ubuntu22.04"
tag = f"{cuda_version}-{flavor}-{os}"

image = (
    modal.Image.from_registry(f"nvidia/cuda:{tag}", add_python="3.11")
    .apt_install("git")
    .pip_install(  # required to build flash-attn
        "ninja",
        "packaging",
        "wheel",
        # "torch",
    )
    .run_commands("pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124",
        "git clone https://github.com/NVIDIA/apex.git",
	"cd apex",
        "pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings \"--build-option=--cpp_ext\" --config-settings \"--build-option=--cuda_ext\" ./"
    )
)

app = modal.App()

@app.function(gpu="a10g", image=image)
@modal.web_endpoint(
    #method="POST", 
    docs=True)
def run_flash_attn(user: str) -> str:
      return f"Hello {user}!"
```

But I am getting this error. Any help regarding this would be appreciated.

```
=> Step 2: RUN git clone https://github.com/NVIDIA/apex.git
Cloning into 'apex'...

=> Step 3: RUN cd apex

=> Step 4: RUN pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" ./
Using pip 24.1.2 from /usr/local/lib/python3.11/site-packages/pip (python 3.11)
ERROR: Directory './' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
Terminating task due to error: failed to run builder command "pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings \"--build-option=--cpp_ext\" --config-settings \"--build-option=--cuda_ext\" ./"

Caused by:
    container exit status: 1
\ Creating objects...
└── 🔨 Created mount C:\Edrive\Modal_Projects\modal_test_GPU.py[Thread-1 (thread_inner)] 2024-07-25T00:23:57-0400 Exception when resolving Image()
Traceback (most recent call last):
  File "C:\Edrive\Bzain\venv\lib\site-packages\modal\_resolver.py", line 147, in load
    return await cached_future
  File "C:\Edrive\Bzain\venv\lib\site-packages\modal\_resolver.py", line 123, in loader
    await obj._load(obj, self, existing_object_id)
  File "C:\Edrive\Bzain\venv\lib\site-packages\modal\image.py", line 445, in _load
    raise RemoteError(f"Image build for {image_id} failed with the exception:\n{result.exception}")
modal.exception.RemoteError: Image build for im-ztjh5hDSXO2EWMd23cCwAM failed with the exception:
task exited with failure, status = exit status: 1
[Thread-1 (thread_inner)] 2024-07-25T00:23:57-0400 Exception when resolving Function(run_flash_attn)
Traceback (most recent call last):
  File "C:\Edrive\Bzain\venv\lib\site-packages\modal\_resolver.py", line 147, in load
    return await cached_future
  File "C:\Edrive\Bzain\venv\lib\site-packages\modal\_resolver.py", line 119, in loader
    await TaskContext.gather(*[self.load(dep) for dep in obj.deps()])
  File "C:\Edrive\Bzain\venv\lib\site-packages\modal\_utils\async_utils.py", line 231, in gather
    results = await asyncio.gather(*(tc.create_task(coro) for coro in coros))
  File "C:\Edrive\Bzain\venv\lib\site-packages\modal\_resolver.py", line 147, in load
    return await cached_future
  File "C:\Edrive\Bzain\venv\lib\site-packages\modal\_resolver.py", line 123, in loader
    await obj._load(obj, self, existing_object_id)
  File "C:\Edrive\Bzain\venv\lib\site-packages\modal\image.py", line 445, in _load
    raise RemoteError(f"Image build for {image_id} failed with the exception:\n{result.exception}")
modal.exception.RemoteError: Image build for im-ztjh5hDSXO2EWMd23cCwAM failed with the exception:
Runner failed with exception: task exited with failure, status = exit status: 1                                                               
Stopping app - uncaught exception raised locally: RemoteError('Image build for im-ztjh5hDSXO2EWMd23cCwAM failed with the exception:\ntask exited with failure, status = exit status: 1').
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Image build for im-ztjh5hDSXO2EWMd23cCwAM failed with the exception:                                                                       │
│ task exited with failure, status = exit status: 1  
```

**Comment by mwaskom** [comment]
Hi, similar to Docker, workdir state is not persisted across the arguments to `Image.run_commands`; you would want something like `cd workdir && pip install .` if you need to run commands in specific locations.

**Comment by AvisP** [comment]
Hi thanks for your response. I tried making the suggested change, but getting the same error...

```
import modal

cuda_version = "12.4.0"  # should be no greater than host CUDA version
flavor = "devel"  #  includes full CUDA toolkit
os = "ubuntu22.04"
tag = f"{cuda_version}-{flavor}-{os}"

image = (
    modal.Image.from_registry(f"nvidia/cuda:{tag}", add_python="3.11")
    .apt_install("git")
    .pip_install(  # required to build flash-attn
        "ninja",
        "packaging",
        "wheel",
        # "torch",
    )
    .run_commands("pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124",
        "git clone https://github.com/NVIDIA/apex.git",
	"cd apex && pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings \"--build-option=--cpp_ext\" --config-settings \"--build-option=--cuda_ext\" ./"
    )
)


app = modal.App()

@app.function(gpu="a10g", image=image)
@modal.web_endpoint(
    #method="POST", 
    docs=True)
def run_flash_attn(user: str) -> str:

    return f"Hello {user}!"
```

**Comment by mwaskom** [comment]
Hi, when I run your code I get

```
subprocess.CalledProcessError: Command '['which', 'clang++']' returned non-zero exit status 1.
```

Which suggests that you need to add `clang` to the image, i.e. via `apt_install`.

**Comment by AvisP** [comment]
I was finally able to run it with the following code and here is the running container. https://modal.com/avisp/main/logs/ap-LLenmzvzFVdz5qUcm0PDgP

I had two follow up questions

1. I think the windows modal version doesn't support auto-reload and I am having to ctrl+C to stop and start the container after making changes. Is there a better way to go about this, as it takes quite a long time for the container to start while installing apex
2. Is there a way to get terminal access to the container? I want to log in and run some python code using apex. I was thinking of trying `modal container exec container-id` but when I tried `modal container list` but it is showing blank.

```
import modal

cuda_version = "12.4.0"  # should be no greater than host CUDA version
flavor = "devel"  #  includes full CUDA toolkit
os = "ubuntu22.04"
tag = f"{cuda_version}-{flavor}-{os}"

image = (
    modal.Image.from_registry(f"nvidia/cuda:{tag}", add_python="3.11")
    .apt_install("git", "clang")
    .pip_install(  # required to build flash-attn
        "ninja",
        "packaging",
        "wheel",
        # "torch",
    )
    .run_commands("pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124",
                  "pip install -v --disable-pip-version-check --no-cache-dir --no-build-isolation --config-settings \"--build-option=--cpp_ext\" --config-settings \"--build-option=--cuda_ext\" git+https://github.com/NVIDIA/apex.git"
    )
)

app = modal.App()

@app.function(gpu="a10g", image=image)
@modal.web_endpoint(
    #method="POST", 
    docs=True)
def run_flash_attn(user: str) -> str:

    return f"Hello {user}!"
```

**Comment by thundergolfer** [comment]
> Is there a way to get terminal access to the container? I want to log in and run some python code using apex. I was thinking of trying modal container exec container-id but when I tried modal container list but it is showing blank.

yes `container exec` works on running containers but there's also `modal shell` which will start a new container and run a shell in it. If `container list` was empty it was likely that your container had already stopped :)

**Comment by mwaskom** [comment]
Closing but feel free to follow up or reach out on Slack for more support!
